### ISSUE TITLE
support recorded script editing 

### ISSUE THREAD

**Issue by adrianna1211** [ruifigueira/playwright-crx#23]
Hi, is there any way to support script editing in playwright inspector?
After I recorded some steps, I want to change the text input so that it won't be clocked by duplication check. 
thx!

**Comment by ruifigueira** [comment]
Unfortunately no.

Chrome extensions don't allow running arbitrary code for security reasons, so this extension doesn't actually execute the code, and rather replays the actions that were stored during the recording. The recorder then knows which line to highlight because it maps which line corresponds to each action.
