### ISSUE TITLE
Playing recorded script option

### ISSUE THREAD

**Issue by othman-fayed** [ruifigueira/playwright-crx#35]
Hello
Why can't i paste the script directly into the extension and play it?

**Comment by ruifigueira** [comment]
Hi, @othman-fayed . Chrome extensions don't allow unsafe-eval, so dynamically change code and evaluating it would not work.

Even the player is not actually evaluating code: every recorded instruction is a structure that we keep and convert to any supported language, and player only iterates over it. That's why you can debug the "code" in Python or java, even if those languages cannot run in the browser.
